resolver: lts-13.25
packages:
- .

extra-deps:
 - containers-0.6.2.1
 - binary-0.8.7.0@sha256:ae3e6cca723ac55c54bbb3fa771bcf18142bc727afd57818e66d6ee6c8044f12,7705

flags: {}

extra-package-dbs: []

nix:
    packages: [zlib.dev, zlib.out, pkgconfig, haskell.compiler.ghc865]
